import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { FeaturedTypes, PageBannerTypes } from "../Types/aboutPageTypes";
import PageBanner from "../components/PageBanner";
import AboutBlock from "../components/AboutBlock";
import FeatureBlock from "../components/FeatureBlock";
import { TeamTypes } from "../Types/homepageTypes";
import Team from "../components/Team";


interface Props {
  bannerData:PageBannerTypes
  aboutBlock:PageBannerTypes
  featurePage:FeaturedTypes
  teamData:TeamTypes[]
}



const About: NextPage<Props> = ({bannerData, aboutBlock, featurePage, teamData}) => {

  const { preTitle: teamPreTitle, title: teamTitle } = bannerData.team_block;

  return (
    <>
      <Head>
        <title>Arhitektur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <PageBanner data={{ preTitle: bannerData.about_block.preTitle }}/>
      <AboutBlock data={aboutBlock} />
      <FeatureBlock data={featurePage}/>
      <Team data={teamData} title={teamPreTitle} pretitle={teamTitle}/>
    </>
  );
};

export default About;



export const getStaticProps:GetStaticProps= async () => {
 
  const resBanner=await fetch(`http://localhost:5001/about_page`)
  const bannerData:PageBannerTypes=await(resBanner.json()) 
  
  const resAbout=await fetch(`http://localhost:5001/about_page`)
  const aboutBlock:PageBannerTypes=await (resAbout.json())

  const resFeature = await fetch(`http://localhost:5001/about_page`)
  const featurePage:FeaturedTypes=await(resFeature.json())
  
  const resTeam=await fetch (`http://localhost:5001/team`)
  const teamData:TeamTypes[]=await(resTeam.json())

  return {
    props: {bannerData, aboutBlock, featurePage, teamData}
  }
}
