import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import { BannerTypes, ServicePageTypes, ServicesTypes, TeamTypes } from "../Types/homepageTypes";
import Services from "../components/Services";
import Team from "../components/Team";



interface Props {
  bannerData:BannerTypes
  servicePageData:ServicePageTypes
  servicesData:ServicesTypes[]
  teamData:TeamTypes[]
  
}

const Home: NextPage<Props> = ({bannerData, servicePageData, servicesData, teamData}) => {


  return (
    <>
      <Head>
        <title>Arhitektur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner data={bannerData}/>
      <Services data={servicePageData} services={servicesData}/>
      <Team data={teamData} pretitle={bannerData.team_block.preTitle} title={bannerData.team_block.title} />
     
    </>
  );
};

export default Home;



export const getStaticProps:GetStaticProps= async () => {
 
  const res=await fetch (`http://localhost:5001/homepage`)
  const bannerData:BannerTypes=await(res.json())
   
  const resServicePage=await fetch (`http://localhost:5001/services_page`)
  const servicePageData:ServicePageTypes=await (resServicePage.json()) 

  const resServices=await fetch(`http://localhost:5001/services`)
  const servicesData:ServicesTypes[]=await(resServices.json())
  
  const resTeam=await fetch (`http://localhost:5001/team`)
  const teamData:TeamTypes[]=await(resTeam.json())


  return {
    props: {bannerData, servicePageData, servicesData,teamData}
  }
}
