import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import PageBanner from "../components/PageBanner";
import { ServicePageTypes, ServicesTypes, TeamTypes } from "../Types/homepageTypes";
import { ServiceBannerType } from "../Types/servisePageTypes";
import Services from "../components/Services";
import Team from "../components/Team";



interface Props {
  pageBanner:ServiceBannerType
  servicePageData:ServicePageTypes
  servicesData:ServicesTypes[]
  teamData:TeamTypes[]
}



const ServicePage: NextPage<Props> = ({pageBanner, servicePageData, servicesData, teamData}) => {
 


  return (
    <>
      <Head>
        <title>Arhitektur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <PageBanner data={{preTitle: pageBanner.services_block.preTitle }}/>
      <Services data={servicePageData} services={servicesData}/>
      <Team data={teamData} pretitle={servicePageData.team_block.preTitle} title={servicePageData.services_block.title} />
    </>
  );
};

export default ServicePage;



export const getStaticProps:GetStaticProps= async () => {
 
  const resBanner=await fetch (`http://localhost:5001/services_page`)
  const pageBanner:ServiceBannerType=await(resBanner.json())

  const resServicePage=await fetch (`http://localhost:5001/services_page`)
  const servicePageData:ServicePageTypes=await (resServicePage.json()) 

  const resServices=await fetch(`http://localhost:5001/services`)
  const servicesData:ServicesTypes[]=await(resServices.json())

  const resTeam=await fetch (`http://localhost:5001/team`)
  const teamData:TeamTypes[]=await(resTeam.json())

  return {
    props: {pageBanner, servicePageData, servicesData, teamData}
  }
}